#
# from scratch attempt at a csv-driven mode=sample eventgen configuration

[destinations.csv]
# eventgen main settings
# mode = sample
# outputMode = splunkstream

# eventgen splunk event settings
# all of these things are supposed to be settable in the .csv file,
# but that seems to have been broken somewhere along the line,
# as the content of the csv was getting echo'd into the events
index = main
host = www.destinations.com
source = weblog
sourcetype = access_custom

# eventgen timing settings
interval = 10
earliest = -10s
lastest = now
count = 3
randomizeCount = .5
randomizeEvents = true

# Replace timestamp
token.0.token = \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}:000
token.0.replacementType = timestamp
token.0.replacement = ["%b %d %H:%M:%S:%f", "%Y-%m-%d %H:%M:%S:%f"]

# Replace external IP
token.1.token = (External-IP)
token.1.replacementType = file
token.1.replacement = $SPLUNK_HOME/etc/apps/destinations/samples/external_ips.sample

# Replace webhosts
token.2.token = (Web-Hosts)
token.2.replacementType = file
token.2.replacement = $SPLUNK_HOME/etc/apps/destinations/samples/webhosts.sample

# Repalce method and URI
token.3.token = (Method-And-URI)
token.3.replacementType = file
token.3.replacement = $SPLUNK_HOME/etc/apps/destinations/samples/destinations-uris.sample

# Replace user agent
token.4.token = (User-Agent)
token.4.replacementType = file
token.4.replacement = $SPLUNK_HOME/etc/apps/destinations/samples/useragents_desktop.sample

# replace response time
token.5.token = (468)
token.5.replacementType = random
token.5.replacement = integer[100:1000]

# replace response bytes
token.6.token = (1488)
token.6.replacementType = random
token.6.replacement = integer[200:4000]

# replace http status codes
token.7.token = (200)
token.7.replacementType = file
token.7.replacement = $SPLUNK_HOME/etc/apps//destinations/samples/destinations-codes.sample

